### ISSUE TITLE
MANAGE_CS1.sh script failed when downloading repo to local

### ISSUE THREAD

**Issue by haoransun93** [spaceconcordia/space-script#14]
Issue with the MANAGE_CS1.sh script failed.
To reproduce:
change the vm sync settings
download the MANAGE_CS1.sh file
running MANAGE_CS1.sh file
repositories are cloned until space-pcd

"Running modules if present...
/home/vagrant/CONSAT1/space-script/modules/environment_module.sh: line 22: NC: command not found
Ensuring directory permissions...
chmod: cannot access "/home/vagrant/space-script/at-runner/at_runner.sh" No such file or directory...
linking /home/apps
ln: failed to create symbolic link /home/apps : File exists
linking /home/logs
ln: failed to create symbolic link '/home/logs' : File exists
linking /home/pipes
ln: failed to create symbolic link '/home/pipes': File exists
linking /home/tgz
ln: failed to create symbolic link '/home/tgz/: File exists
Yield on /home/vagrant/CONSAT1/space-script/modules/environment_module.sh

**Comment by haoransun93** [comment]
rerunning MANAGE_CS1.sh seems to fix it.

**Comment by SpaceShawn** [comment]
Can't reproduce, seems to be fixed after my last update
